### ISSUE TITLE
NPM install errors with Node 10.4.0

### ISSUE THREAD

**Issue by loftyduck** [ionic-team/stencil-component-starter#59]
**Stencil version:** 
```
@stencil/core@0.9.1
```

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Output from npm install:

```
> fsevents@1.1.3 install /Users/natel/healthland/stencil-components/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
In file included from ../fsevents.cc:85  handler->Call(3, argv);:

           ^
../src/methods.cc:14:12: ../../nan/nan.h:warning1617: :3: note'Call':  is'Call'  deprecatedhas  [-Wdeprecated-declarations]been 
explicitly marked deprecated here
  handler->Call(3, argv);
           ^
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:1617:3:../../nan/nan.h :98:note40: : 'Call' hasnote : been expandedexplicitly  frommarked  macrodeprecated  'NAN_DEPRECATED'here

  NAN_DEPRECATED inline v8::Local<v8::Value># define NAN_DEPRECATED __attribute__((deprecated))

  ^                                       ^

../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning generated.
1 warning generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/natel/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/natel/.nvm/versions/node/v10.4.0/bin/node" "/Users/natel/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/natel/healthland/stencil-components/node_modules/fsevents
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
  SOLINK_MODULE(target) Release/fse.node
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/natel/.nvm/versions/node/v10.4.0/bin/node /Users/natel/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/natel/healthland/stencil-components/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/Users/natel/.nvm/versions/node/v10.4.0/bin/node" "/Users/natel/healthland/stencil-components/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/natel/healthland/stencil-components/node_modules/fsevents
node-pre-gyp ERR! node -v v10.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/natel/.nvm/versions/node/v10.4.0/bin/node /Users/natel/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
  COPY /Users/natel/healthland/stencil-components/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stampial postinstall 6628
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 741 packages from 458 contributors and audited 20780 packages in 14s
found 160 vulnerabilities (44 low, 108 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Expected behavior:**
npm install should succeed with exit status 0.  The package.json could be updated to specify the supported NPM & node versions.

**Steps to reproduce:**
- Install Node version 10.4.0
- git clone https://github.com/ionic-team/stencil-component-starter.git stencil-components
- cd stencil-components
- npm install

**Related code:**

**Other information:**
The NPM install works fine if I use node v8.9.4

**Comment by adamdbradley** [comment]
Ok thanks for the report, we'll get this fixed up.

**Comment by kensodemann** [comment]
Tested with the latest version of the starter on and node versions 8.12.0 and 10.11.0 on the following platforms: Mac, Linux, Windows.  It worked in all cases, so I am going to close this. Please let me know if you still see this issue with the latest version of the starter.
